#!/bin/sh -e
# postinst script for sift
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

if [ "$1" != configure ]; then
	exit 0
fi


create_sift_user() {
	if ! getent passwd sift >/dev/null; then
		adduser --quiet 
	fi
}

create_directories() {
	mkdir -p /cases
	mkdir -p /mnt/usb
	mkdir -p /mnt/vss
	mkdir -p /mnt/shadow

	for NUM in {1..5}
	do
		mkdir -p /mnt/windows_mount$NUM
		mkdir -p /mnt/ewf$NUM
	done
 
	for NUM in {1..30}
	do
		mkdir -p /mnt/shadow/vss$NUM
	done
}

configure_sift_user() {
	sudo -u sift gsettings set org.gnome.desktop.background picture-uri file:///usr/share/sift/resources/forensics_blue.jpg
	sudo -u sift dconf write /desktop/unity/launcher/favorites "['firefox.desktop', 'gnome-screenshot.desktop', 'gcalctool.desktop', 'bless.desktop', 'dff.desktop', 'autopsy.desktop', 'wireshark.desktop']"

	#sudo -u sift ln -s /cases /home/sift/Desktop/cases
	#sudo -u sift ln -s /mnt /home/sift/Desktop/mount_points
	#sudo -u sift ln -s /usr/share/sift/resources/sans-dfir-poster.pdf /home/sift/Desktop/SANS_DFIR_Poster.pdf
}

configure_appliance() {
	gsettings set com.canonical.unity-greeter background file:///usr/share/sift/images/forensics_blue.jpg
	gsettings set com.canonical.unity-greeter logo file:///usr/share/sift/images/dfir_logo.jpg
}

# Run the functions
create_sift_user
create_directories
configure_sift_user
configure_appliance

exit 0
